# Generated by Django 4.2 on 2023-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={"verbose_name": "Наполнение сайта",},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
    ]
