# Generated by Django 4.2 on 2023-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personalpage",
            "0003_alter_textcontainer_options_textcontainer_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название страницы"),
                ),
                (
                    "title",
                    models.CharField(
                        default=None, max_length=255, verbose_name="Заголовок h1"
                    ),
                ),
                ("text", models.TextField(verbose_name="Контент")),
            ],
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
        migrations.DeleteModel(name="TextContainer",),
    ]
