# Generated by Django 4.2 on 2023-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalpage", "0005_aboutpagecontent_pricespagecontent_service_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricespagecontent",
            options={
                "verbose_name": "Страница Цены",
                "verbose_name_plural": "Страница Цены",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "verbose_name": "Таблица Цен",
                "verbose_name_plural": "Таблица цен",
            },
        ),
        migrations.RemoveField(model_name="pricespagecontent", name="text",),
        migrations.AddField(
            model_name="pricespagecontent",
            name="text_1",
            field=models.TextField(default=None, verbose_name="Контент 1"),
        ),
        migrations.AddField(
            model_name="pricespagecontent",
            name="text_2",
            field=models.TextField(default=None, verbose_name="Контент 2"),
        ),
    ]
