# Generated by Django 4.2 on 2023-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalpage", "0006_alter_pricespagecontent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricespagecontent",
            name="text_3",
            field=models.TextField(default=None, verbose_name="Контент 3"),
        ),
    ]
